### ISSUE TITLE
Why latest released album title is on center?

### ISSUE THREAD

**Issue by mertturunc** [khanhas/Spicetify#14]
![image](https://user-images.githubusercontent.com/16109023/39307606-fc2621ae-496b-11e8-9555-b7ce71a45877.png)

**Comment by khanhas** [comment]
Wow, I can't believe I never notice that.
Choose Edit CSS and add this to your user.css file:
```css
.card-horizontal-interior-wrapper .card-info-title {
	text-align: start !important;
}
```
