### ISSUE TITLE
SpicetifyDefault theme color issue

### ISSUE THREAD

**Issue by mertturunc** [khanhas/Spicetify#15]
![2018-04-26_16-28-54](https://user-images.githubusercontent.com/16109023/39308770-f61aaba6-496e-11e8-8d42-1bccb71dc246.gif)

**Comment by khanhas** [comment]
Edit CSS and add this:
```css
.tl-row.selected:hover .tl-cell {
	background: var(--modspotify_scrollbar_fg_and_selected_row_bg) !important;
}
```
